version: '3.8'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=db1
    volumes:
      - ./db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./myown.cfg:/etc/mysql/conf.d/my-own.cnf

# docker-compose up -d
# 
# Backup database to script
# docker exec -it mariadb mysqldump -u root -psecret db1 > db1.sql
# or
# docker exec mariadb sh -c 'exec mysqldump -u root -p"$MYSQL_ROOT_PASSWORD" db1' > db1.sql