version: '3.8'

services:
  backup:
    image: postgres:15-alpine
    networks:
      - traefik-public
    depends_on:
      - db
    volumes:
      - backup_vol:/backup
    command: >
      pg_dump --host db -F c -f /backup/geonames.dump --username=postgres geonames
    environment:
      - PGPASSWORD=secret
      - POSTGRES_PASSWORD=secret

volumes:
  backup_vol: